image: node:10

pipelines:
  default:
    - step:
        name: Deploy to Lambda
        deployment: production
        script:
        - npm install -g serverless
        - npm install
        - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
        - serverless deploy