frameworkVersion: '^2.1.1'
service: belfort-api
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  memorySize: 128
plugins:
  - serverless-domain-manager
custom:
  customDomain:
    # crazy that the only way to change this is via their cli...
    domainName: "-"
    certificateName: be180.co.uk
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
functions:
  app:
    handler: server.handler
    description: the app
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true