service: belfort-api
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  memorySize: 128
custom:
  customDomain:
    domainName: api.be180.co.uk
    certificateName: be180.co.uk
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
functions:
  app:
    handler: server.handler
    description: the app
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true